# Generated by Django 2.2.28 on 2023-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdwTZ9RvEp9f8Twey_YzSo7q_fIt7T3bAe_SWMMozM_ZC2s1Kw4HaFGt7ozxoFL0R4D5k&usqp=CAU', max_length=600),
        ),
    ]
